[project]
name = "vscode-dataanalysisagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sachinshettys90", email = "sachinshettyss85@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.16.0",
    "langsmith>=0.13.0",
    "yfinance>=1.7.0",
]

[project.scripts]
vscode-dataanalysisagent = "vscode_dataanalysisagent:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
